In [2]:
import numpy as np
v = np.array([1,2,3,4,5,6])
condition = v>=4
new_arr = np.where(condition , -1 , v)
print(condition)

[False False False  True  True  True]

In [ ]:
pip install pandas

In [ ]:
import pandas as pd 
df = pd.read_csv('test.csv')
df.head()
df.tail()

In [6]:
s = pd.Series([1,2,3,4] , index=['a','b','c' , 'd'])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
data= [[1,444,"abc"],
       [2,555,'def'],
       [3,666,'fhi'],
       [4,777,'xyz']]
df = pd.DataFrame(data, columns=['index' , 'id' , 'name'] )
display(df)
df.dtypes
df['id'].dtypes
df['id'] = df['id'].astype('category')
df.dtypes

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

index       int64
id       category
name       object
dtype: object

In [14]:
cols = ['index' , 'id']
df[cols] = df[cols].astype('category')
df.dtypes
df.describe()

        index   id name
count       4    4    4
unique      4    4    4
top         1  444  abc
freq        1    1    1

In [19]:
data= [[1,444,"abc"],
       [2,555,'def'],
       [3,666,'fhi'],
       [4,777,'xyz']]
df = pd.DataFrame(data, columns=['index' , 'id' , 'name'] )
display(df)
df['id'] = df['id'].astype('category')
df.describe(include="category")

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

         id
count     4
unique    4
top     444
freq      1

In [21]:
df['id'].unique()
df.columns

Index(['index', 'id', 'name'], dtype='object')

In [ ]:
data= [[1,444,"abc"],
       [2,555,'def'],
       [3,666,'fhi'],
       [4,777,'xyz']]
df = pd.DataFrame(data, columns=['index' , 'id' , 'name'] )
display(df)
df['id'].max()
df['id'].idxmax()
df['id'].idxmin()

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

0

In [31]:
df.info()
df.max()
df.values
df.replace(666,'888')
df.replace({444,'aya' , 888 , '777'})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   4 non-null      int64
 1   id      4 non-null      int64
 2   name    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

C:\Users\ah383\AppData\Local\Temp\ipykernel_3176\1944804083.py:5: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df.replace({444,'aya' , 888 , '777'})

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

In [33]:
def duplicated(x):
    return x*2

df['id'].apply(duplicated)
df['id'].apply(lambda x : x*2)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [42]:
df.id.iloc[2]
df.iloc[:, 0:2]
display(df)

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

In [ ]:
df['new_col']  = df.name + df.name
df
df.drop('new_col' , axis=1)

   index   id name
0      1  444  abc
1      2  555  def
2      3  666  fhi
3      4  777  xyz

In [ ]:
new_row = {'id':9, 'index' : "5" , 'name' : 'ahmed'}
df = pd.concat([df ,pd.DataFrame(new_row) ])

In [49]:
null = df.isnull()
pd.DataFrame(null.sum()).T

   index  id  name  new_col
0      0   0     0        0

In [50]:
def check_null(df):
    return pd.DataFrame(df.sum()).T
check_null(null)

   index  id  name  new_col
0      0   0     0        0

In [ ]:
df.dropna(subset=['id']) #drop null from speific item